/**
 * Inlines README.md into a JS module the worker can import.
 *
 * Why generate instead of importing the .md directly: wrangler could load it with a `Text` rule, but
 * then `src/index.js` would no longer parse under plain Node — and the routing tests import that
 * module directly, with no bundler in the way. Generating a .js module keeps one source of truth (the
 * README) and keeps the tests runnable with nothing but `node`.
 *
 * Runs automatically before `npm test` and `npm run deploy`.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, '..', 'README.md');
const out = join(here, '..', 'src', 'readme.generated.js');

const text = readFileSync(src, 'utf8');

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  '// GENERATED by scripts/embed-readme.mjs — do not edit; edit ../README.md instead.\n' +
    `export default ${JSON.stringify(text)};\n`,
  'utf8',
);

console.log(`embed-readme: ${text.length} chars -> src/readme.generated.js`);
