using System;
using System.Collections.Generic;
using System.Numerics;

namespace Proteus.Services;

/// <summary>
/// Where a real hat's rim sits, measured once and baked in: the plane the hat-compat cut works from. Baked and
/// single-hat because <c>atr_kam</c> is one mask for every head piece. The reference is the Wrangler's Hat
/// (<c>e0380</c>), chosen because it covers LITTLE: a hat covering more just hides extra hair.
/// <para/>
/// The table is generated; do not hand-edit it. Re-run
/// <c>HatCompatDiagTests.BakeTheReferenceHatProfile</c> with <c>PROTEUS_HAT_SET=380</c> and paste.
/// </summary>
internal static class HatProfile
{
    /// <summary>
    /// A rim plane in head-centre-relative metres: hair is under the hat where <c>y &gt; A*x + B*z + C</c>.
    /// Relative, so the wearer's own head centre re-anchors it. <c>A</c> (left-right) is fitted as zero, since
    /// head and hat are symmetric.
    /// </summary>
    private sealed record Plane(float A, float B, float C);

    // ── generated ───────────────────────────────────────────────────────────
    // Generated by HatCompatDiagTests.BakeTheReferenceHatProfile.
    // Wrangler's Hat, equipment set e0380, read from the game's own data.
    // The rim of the part that WRAPS the head (brim excluded, outliers over 25 mm dropped), relative to the head
    // centre measured from that race's vanilla face.
    private static readonly Dictionary<string, Plane> Baked = new(StringComparer.OrdinalIgnoreCase)
    {
        ["c0101"] = new(0f, 0.11893f, 0.0187f),
        ["c0201"] = new(0f, 0.13684f, 0.01405f),
        ["c0501"] = new(0f, 0.10789f, 0.02377f),
        ["c0601"] = new(0f, 0.13456f, 0.0198f),
        ["c0701"] = new(0f, 0.10432f, 0.0018f),
        ["c0801"] = new(0f, 0.11801f, -0.00058f),
        ["c0901"] = new(0f, 0.13784f, 0.03061f),
        ["c1001"] = new(0f, 0.0605f, 0.02234f),
        ["c1101"] = new(0f, 0.09287f, -0.00145f),
        ["c1301"] = new(0f, 0.10362f, 0.02236f),
        ["c1401"] = new(0f, 0.1909f, 0.00247f),
        ["c1701"] = new(0f, 0.09938f, 0.01184f),
        ["c1801"] = new(0f, 0.11466f, 0.01233f),
    };

    /// <summary>
    /// The baked rim for a race code ("0801", or "c0801"), following the game's own EQDP fall-through
    /// (<see cref="ModelRace.Fallback"/>) when that race has no measurement of its own.
    /// </summary>
    private static Plane? For(string? raceCode)
    {
        if (string.IsNullOrEmpty(raceCode)) return null;
        var code = raceCode.StartsWith('c') ? raceCode : "c" + raceCode;
        if (code.Length > 5) code = code[..5];

        if (ModelRace.Index(code[1..]) is not { } n) return null;
        for (int hop = 0; hop < 8 && n >= 1; hop++)
        {
            if (Baked.TryGetValue($"c{n:D2}01", out var hit)) return hit;
            int next = ModelRace.Fallback(n);
            if (next == n) break;
            n = next;
        }
        return null;
    }

    /// <summary>Whether any measurement exists for this race, after fall-through.</summary>
    internal static bool Known(string? raceCode) => For(raceCode) != null;

    /// <summary>
    /// Whether <paramref name="p"/> sits above the hat's rim, with <paramref name="centre"/> the head centre
    /// from the wearer's face model. False for a race with no baked rim.
    /// </summary>
    internal static bool UnderTheHat(string? raceCode, Vector3 p, Vector3 centre)
        => AboveRim(raceCode, p, centre) > 0f;

    /// <summary>
    /// How far above the hat's rim <paramref name="p"/> sits, in metres: negative below it, and
    /// <see cref="float.NegativeInfinity"/> for a race with no baked rim, so nothing is cut on a guess.
    /// </summary>
    internal static float AboveRim(string? raceCode, Vector3 p, Vector3 centre)
    {
        if (For(raceCode) is not { } q) return float.NegativeInfinity;
        var d = p - centre;
        return d.Y - (q.A * d.X + q.B * d.Z + q.C);
    }
}
