using System;
using System.Collections.Generic;
using System.Numerics;

namespace Proteus.Services;

/// <summary>
/// Where a real hat's rim sits, measured once and baked in — the plane the hat-compat cut works from.
/// <para/>
/// WHY BAKED, and why ONE hat. The cut is written into a hairstyle as a single <c>atr_kam</c> mask, and the
/// game turns that mask off whenever ANY head piece is worn. There is nowhere to put a per-hat answer, so
/// measuring the equipped hat at runtime is not merely expensive, it is unimplementable — and the game's own
/// hat-compatible hair works exactly the same way, with one fixed answer per hairstyle.
/// <para/>
/// WHY THIS HAT. The reference is the <b>Wrangler's Hat</b>, equipment set <c>e0380</c>. The rule is to
/// pick a hat that covers LITTLE: a real hat covering MORE than the reference simply hides the extra hair,
/// while one covering LESS leaves a bald gap that nothing can fill. The Calfskin Rider's Cap (e6116) was
/// measured first and is the wrong end of that — its rim sits about 7 mm lower, so it over-cut for every
/// hat that perches higher, which is most of them.
/// <para/>
/// WHY A PLANE, and not the hat's surface. A radial profile of the hat was tried first and cannot express
/// "below the rim": a ray from the head centre pointing down-and-back still hits the cap's band on its way
/// out, so that direction reads as covered and every hair along the ray goes with it, rim or no rim. That
/// cut the nape and the temples far too low however the tolerances were set. The rim is what decides what a
/// hat hides, and the rim is very nearly a plane.
/// <para/>
/// It is not exactly one. Measured column by column, the rim runs from about -10 mm at the back to +32 mm
/// at the front of a Midlander's head centre, and a plane fitted through it leaves a worst residual of
/// 13-23 mm depending on race. That is the accuracy this feature has, and it is why the old
/// hand-picked <c>HatLine</c> of 22 mm was neither obviously right nor obviously wrong: it sits inside the
/// spread, but flat, with no front-to-back tilt at all.
/// <para/>
/// The table is generated; do not hand-edit it. Re-run
/// <c>HatCompatDiagTests.BakeTheReferenceHatProfile</c> with <c>PROTEUS_HAT_SET=380</c> and paste.
/// </summary>
internal static class HatProfile
{
    /// <summary>
    /// A rim plane in head-centre-relative metres: hair is under the hat where <c>y &gt; A*x + B*z + C</c>.
    /// <para/>
    /// Relative to the centre rather than absolute, so the wearer's OWN measured head centre re-anchors it
    /// and a face mod moves the hat with the head instead of leaving it floating.
    /// <para/>
    /// <c>B</c> carries the front-to-back tilt, which is most of the shape: a hat's rim is lower at the nape
    /// than it is under the brim. <c>A</c> is left-to-right and is FITTED AS ZERO — a head and a hat are
    /// bilaterally symmetric, so that term can only fit noise, and left free it reached -0.038 on some
    /// races. It is kept in the record so the plane reads as a plane rather than a special case.
    /// </summary>
    private sealed record Plane(float A, float B, float C);

    // ── generated ───────────────────────────────────────────────────────────
    // Generated by HatCompatDiagTests.BakeTheReferenceHatProfile on 2026-09-11.
    // Wrangler's Hat, equipment set e0380, read from the game's own data.
    // The rim of the part that WRAPS the head, relative to the head centre measured from that race's
    // vanilla face. The brim is excluded, or its underside drags the front of the plane down; the fit is
    // re-run three times dropping anything more than 25 mm off, or the lining's top edge (85 mm up where
    // the rim beside it is 2 mm) gets as much weight as the thirty columns that agree.
    private static readonly Dictionary<string, Plane> Baked = new(StringComparer.OrdinalIgnoreCase)
    {
        ["c0101"] = new(0f, 0.11893f, 0.0187f),
        ["c0201"] = new(0f, 0.13684f, 0.01405f),
        ["c0501"] = new(0f, 0.10789f, 0.02377f),
        ["c0601"] = new(0f, 0.13456f, 0.0198f),
        ["c0701"] = new(0f, 0.10432f, 0.0018f),
        ["c0801"] = new(0f, 0.11801f, -0.00058f),
        ["c0901"] = new(0f, 0.13784f, 0.03061f),
        ["c1001"] = new(0f, 0.0605f, 0.02234f),
        ["c1101"] = new(0f, 0.09287f, -0.00145f),
        ["c1301"] = new(0f, 0.10362f, 0.02236f),
        ["c1401"] = new(0f, 0.1909f, 0.00247f),
        ["c1701"] = new(0f, 0.09938f, 0.01184f),
        ["c1801"] = new(0f, 0.11466f, 0.01233f),
    };

    /// <summary>
    /// The baked rim for a race code ("0801", or "c0801"), following the game's own EQDP fall-through when
    /// that race has no measurement of its own.
    /// <para/>
    /// Falling through is right rather than convenient: the cap does not ship a model for every race, and
    /// where it does not the game itself loads another race's and deforms it onto the wearer.
    /// <see cref="ModelRace.Fallback"/> is that same table.
    /// </summary>
    private static Plane? For(string? raceCode)
    {
        if (string.IsNullOrEmpty(raceCode)) return null;
        var code = raceCode.StartsWith('c') ? raceCode : "c" + raceCode;
        if (code.Length > 5) code = code[..5];

        if (ModelRace.Index(code[1..]) is not { } n) return null;
        for (int hop = 0; hop < 8 && n >= 1; hop++)
        {
            if (Baked.TryGetValue($"c{n:D2}01", out var hit)) return hit;
            int next = ModelRace.Fallback(n);
            if (next == n) break;
            n = next;
        }
        return null;
    }

    /// <summary>Whether any measurement exists for this race, after fall-through.</summary>
    internal static bool Known(string? raceCode) => For(raceCode) != null;

    /// <summary>
    /// Whether <paramref name="p"/> sits above the hat's rim, and so under the hat — with
    /// <paramref name="centre"/> the head centre measured from the wearer's own face model.
    /// <para/>
    /// False for a race with no baked rim, which means no cut at all rather than a guess.
    /// </summary>
    internal static bool UnderTheHat(string? raceCode, Vector3 p, Vector3 centre)
        => AboveRim(raceCode, p, centre) > 0f;

    /// <summary>
    /// How far above the hat's rim <paramref name="p"/> sits, in metres — negative below it, and
    /// <see cref="float.NegativeInfinity"/> for a race with no baked rim, so nothing is ever cut on a guess.
    /// <para/>
    /// The signed distance rather than a yes/no, because the cut wants a BAND and not just a side: hair
    /// immediately above the rim is kept and flattened rather than deleted, so that a hat riding a little
    /// higher than the reference shows flattened hair instead of scalp. See <c>HatCompatSolve.RingHeight</c>.
    /// </summary>
    internal static float AboveRim(string? raceCode, Vector3 p, Vector3 centre)
    {
        if (For(raceCode) is not { } q) return float.NegativeInfinity;
        var d = p - centre;
        return d.Y - (q.A * d.X + q.B * d.Z + q.C);
    }
}
